"""edit and add models

Revision ID: 145d79d90bea
Revises: dc8106bbff35
Create Date: 2025-10-04 11:29:34.477296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145d79d90bea'
down_revision: Union[str, Sequence[str], None] = 'dc8106bbff35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company', sa.Column('email', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('email', sa.String(), nullable=False))
    op.add_column('managers', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'email')
    op.drop_column('employees', 'email')
    op.drop_column('company', 'email')
    op.drop_table('expenses')
    # ### end Alembic commands ###
